"""fix relationship between Customer and Order

Revision ID: 150a85df141d
Revises: fb3e80d5fb51
Create Date: 2024-12-17 10:44:49.557209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '150a85df141d'
down_revision = 'fb3e80d5fb51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('platform_product_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'platform_product_id', name='uix_platform_product')
    )
    op.create_table('order_line_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('platform_message_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('sent_at',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfillment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('platform_order_id',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=50),
               nullable=False)
        batch_op.alter_column('order_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint('uix_platform_order', ['platform', 'platform_order_id'])
        batch_op.drop_column('tracking_number')

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('is_encrypted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('setting', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_encrypted',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_constraint('uix_platform_order', type_='unique')
        batch_op.alter_column('order_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('platform_order_id',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('fulfillment_status')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('sent_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('platform_message_id',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('platform',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    op.drop_table('order_line_item')
    op.drop_table('product')
    # ### end Alembic commands ###
