"""add tracking fields to orders

Revision ID: 673c747441e9
Revises: 150a85df141d
Create Date: 2024-12-17 10:52:23.420746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673c747441e9'
down_revision = '150a85df141d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_carrier', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('tracking_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('tracking_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('tracking_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('estimated_delivery_date')
        batch_op.drop_column('tracking_updated_at')
        batch_op.drop_column('tracking_url')
        batch_op.drop_column('tracking_status')
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('shipping_carrier')

    # ### end Alembic commands ###
